# Generated by Django 2.1.4 on 2018-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181210_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='department',
            field=models.CharField(default='CSE', max_length=5),
        ),
    ]
