# Generated by Django 2.1.4 on 2018-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181211_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventCode',
            field=models.CharField(default='CSCC', max_length=10),
        ),
    ]
